export async function GET(request: Request) {
	const Songs = [
		{ Name: 'Dream On', Artist: 'Aerosmith', Difficulty: 'Easy', Index: 0 },
		{ Name: 'Respect', Artist: 'Aretha Franklin', Difficulty: 'Easy', Index: 1 },
		{ Name: 'Sk8er Boi', Artist: 'Avril Lavigne', Difficulty: 'Easy', Index: 2 },
		{ Name: "Stayin' Alive", Artist: 'Bee Gees', Difficulty: 'Easy', Index: 3 },
		{ Name: 'Single Ladies', Artist: 'Beyoncé', Difficulty: 'Easy', Index: 4 },
		{ Name: 'All the Small Things', Artist: 'blink-182', Difficulty: 'Easy', Index: 5 },
		{ Name: 'My Band', Artist: 'D12', Difficulty: 'Easy', Index: 6 },
		{ Name: 'Feel Good Inc.', Artist: 'Gorillaz', Difficulty: 'Easy', Index: 7 },
		{ Name: 'Love Will Tear Us Apart', Artist: 'Joy Division', Difficulty: 'Easy', Index: 8 },
		{ Name: 'Since U Been Gone', Artist: 'Kelly Clarkson', Difficulty: 'Easy', Index: 9 },
		{ Name: 'Master of Puppets', Artist: 'Metallica', Difficulty: 'Easy', Index: 10 },
		{ Name: "Father's Day", Artist: 'Method Max, Redman', Difficulty: 'Easy', Index: 11 },
		{ Name: 'Wannabe', Artist: 'Spice Girls', Difficulty: 'Easy', Index: 12 },
		{ Name: 'In Too Deep', Artist: 'Sum 41', Difficulty: 'Easy', Index: 13 },
		{ Name: 'Chop Suey!', Artist: 'System of a Down', Difficulty: 'Easy', Index: 14 },
		{ Name: 'Teenage Dirtbag', Artist: 'Wheatus', Difficulty: 'Easy', Index: 15 },
		{ Name: 'The Four Seasons', Artist: 'Antonio Vivaldi', Difficulty: 'Medium', Index: 16 },
		{ Name: 'Bat Country', Artist: 'Avenged Sevenfold', Difficulty: 'Medium', Index: 17 },
		{ Name: 'Paranoid', Artist: 'Black Sabbath', Difficulty: 'Medium', Index: 18 },
		{ Name: 'Insane in the Brain', Artist: 'Cypress Hill', Difficulty: 'Medium', Index: 19 },
		{ Name: 'Be Quiet and Drive (Far Away)', Artist: 'Deftones', Difficulty: 'Medium', Index: 20 },
		{ Name: 'Personal Jesus', Artist: 'Depeche Mode', Difficulty: 'Medium', Index: 21 },
		{ Name: 'Nessun Dorma', Artist: 'Giacomo Puccini', Difficulty: 'Medium', Index: 22 },
		{ Name: 'Genesis', Artist: 'Grimes', Difficulty: 'Medium', Index: 23 },
		{ Name: 'Aqualung', Artist: 'Jethro Tull', Difficulty: 'Medium', Index: 24 },
		{ Name: 'Bet On It', Artist: 'Joshua Bassett', Difficulty: 'Medium', Index: 25 },
		{ Name: 'Breaking the Law', Artist: 'Judas Priest', Difficulty: 'Medium', Index: 26 },
		{ Name: 'United In Grief', Artist: 'Kendrick Lamar', Difficulty: 'Medium', Index: 27 },
		{ Name: 'I Bet on Losing Dogs', Artist: 'Mitski', Difficulty: 'Medium', Index: 28 },
		{ Name: 'Super Bass', Artist: 'Nicki Minaj', Difficulty: 'Medium', Index: 29 },
		{ Name: 'I Wanna Be Sedated', Artist: 'Ramones', Difficulty: 'Medium', Index: 30 },
		{ Name: 'Before I Forget', Artist: 'Slipknot', Difficulty: 'Medium', Index: 31 },
		{ Name: 'Dreams', Artist: 'The Cranberries', Difficulty: 'Medium', Index: 32 },
		{ Name: "Boys Don't Cry", Artist: 'The Cure', Difficulty: 'Medium', Index: 33 },
		{ Name: 'See You Again', Artist: 'Tyler, The Creator', Difficulty: 'Medium', Index: 34 },
		{ Name: 'hand crushed by a mallet', Artist: '100 gecs', Difficulty: 'Hard', Index: 35 },
		{ Name: 'Fire in the Sky', Artist: 'Anderson .Paak', Difficulty: 'Hard', Index: 36 },
		{ Name: 'Use Me', Artist: 'Beans & Fatback', Difficulty: 'Hard', Index: 37 },
		{ Name: 'No Cap', Artist: 'Blake and Miles', Difficulty: 'Hard', Index: 38 },
		{ Name: 'Sober', Artist: 'Childish Gambino', Difficulty: 'Hard', Index: 39 },
		{ Name: 'Awake', Artist: 'Electric Guest', Difficulty: 'Hard', Index: 40 },
		{ Name: 'Dreams', Artist: 'Fleetwood Mac', Difficulty: 'Hard', Index: 41 },
		{ Name: 'March Madness', Artist: 'Future', Difficulty: 'Hard', Index: 42 },
		{ Name: 'When They Fight, They Fight', Artist: 'Generationals', Difficulty: 'Hard', Index: 43 },
		{ Name: 'Rumble And Sway', Artist: 'Jamie N Commons', Difficulty: 'Hard', Index: 44 },
		{ Name: 'Dang!', Artist: 'Mac Miller', Difficulty: 'Hard', Index: 45 },
		{ Name: 'So Rich, So Pretty', Artist: 'Mickey Avalon', Difficulty: 'Hard', Index: 46 },
		{ Name: 'My Heroine', Artist: 'Silverstein', Difficulty: 'Hard', Index: 47 },
		{ Name: 'Grace', Artist: 'Surfaces', Difficulty: 'Hard', Index: 48 },
		{ Name: 'Highwayman', Artist: 'The Highwaymen', Difficulty: 'Hard', Index: 49 },
		{ Name: 'Reflections', Artist: 'The Neighbourhood', Difficulty: 'Hard', Index: 50 },
	]
	return new Response(JSON.stringify(Songs))
}
