export async function GET(request: Request) {
	const Songs = [
		{ Name: "Dream On", Artist: "Aerosmith", Difficulty: "Easy" },
		{ Name: "Respect", Artist: "Aretha Franklin", Difficulty: "Easy" },
		{ Name: "Sk8er Boi", Artist: "Avril Lavigne", Difficulty: "Easy" },
		{ Name: "Stayin' Alive", Artist: "Bee Gees", Difficulty: "Easy" },
		{ Name: "Single Ladies", Artist: "Beyoncé", Difficulty: "Easy" },
		{
			Name: "All the Small Things",
			Artist: "blink-182",
			Difficulty: "Easy",
		},
		{ Name: "My Band", Artist: "D12", Difficulty: "Easy" },
		{ Name: "Feel Good Inc.", Artist: "Gorillaz", Difficulty: "Easy" },
		{
			Name: "Love Will Tear Us Apart",
			Artist: "Joy Division",
			Difficulty: "Easy",
		},
		{
			Name: "Since U Been Gone",
			Artist: "Kelly Clarkson",
			Difficulty: "Easy",
		},
		{ Name: "Master of Puppets", Artist: "Metallica", Difficulty: "Easy" },
		{
			Name: "Father's Day",
			Artist: "Method Max, Redman",
			Difficulty: "Easy",
		},
		{ Name: "Wannabe", Artist: "Spice Girls", Difficulty: "Easy" },
		{ Name: "In Too Deep", Artist: "Sum 41", Difficulty: "Easy" },
		{ Name: "Chop Suey!", Artist: "System of a Down", Difficulty: "Easy" },
		{ Name: "Teenage Dirtbag", Artist: "Wheatus", Difficulty: "Easy" },
		{
			Name: "The Four Seasons",
			Artist: "Antonio Vivaldi",
			Difficulty: "Medium",
		},
		{
			Name: "Bat Country",
			Artist: "Avenged Sevenfold",
			Difficulty: "Medium",
		},
		{ Name: "Paranoid", Artist: "Black Sabbath", Difficulty: "Medium" },
		{
			Name: "Insane in the Brain",
			Artist: "Cypress Hill",
			Difficulty: "Medium",
		},
		{
			Name: "Be Quiet and Drive (Far Away)",
			Artist: "Deftones",
			Difficulty: "Medium",
		},
		{
			Name: "Personal Jesus",
			Artist: "Depeche Mode",
			Difficulty: "Medium",
		},
		{
			Name: "Nessun Dorma",
			Artist: "Giacomo Puccini",
			Difficulty: "Medium",
		},
		{ Name: "Genesis", Artist: "Grimes", Difficulty: "Medium" },
		{ Name: "Aqualung", Artist: "Jethro Tull", Difficulty: "Medium" },
		{ Name: "Bet On It", Artist: "Joshua Bassett", Difficulty: "Medium" },
		{
			Name: "Breaking the Law",
			Artist: "Judas Priest",
			Difficulty: "Medium",
		},
		{
			Name: "United In Grief",
			Artist: "Kendrick Lamar",
			Difficulty: "Medium",
		},
		{
			Name: "I Bet on Losing Dogs",
			Artist: "Mitski",
			Difficulty: "Medium",
		},
		{ Name: "Super Bass", Artist: "Nicki Minaj", Difficulty: "Medium" },
		{ Name: "I Wanna Be Sedated", Artist: "Ramones", Difficulty: "Medium" },
		{ Name: "Before I Forget", Artist: "Slipknot", Difficulty: "Medium" },
		{ Name: "Dreams", Artist: "The Cranberries", Difficulty: "Medium" },
		{ Name: "Boys Don't Cry", Artist: "The Cure", Difficulty: "Medium" },
		{
			Name: "See You Again",
			Artist: "Tyler, The Creator",
			Difficulty: "Medium",
		},
		{
			Name: "hand crushed by a mallet",
			Artist: "100 gecs",
			Difficulty: "Hard",
		},
		{
			Name: "Fire in the Sky",
			Artist: "Anderson .Paak",
			Difficulty: "Hard",
		},
		{ Name: "Use Me", Artist: "Beans & Fatback", Difficulty: "Hard" },
		{ Name: "No Cap", Artist: "Blake and Miles", Difficulty: "Hard" },
		{ Name: "Sober", Artist: "Childish Gambino", Difficulty: "Hard" },
		{ Name: "Awake", Artist: "Electric Guest", Difficulty: "Hard" },
		{ Name: "Dreams", Artist: "Fleetwood Mac", Difficulty: "Hard" },
		{ Name: "March Madness", Artist: "Future", Difficulty: "Hard" },
		{
			Name: "When They Fight, They Fight",
			Artist: "Generationals",
			Difficulty: "Hard",
		},
		{
			Name: "Rumble And Sway",
			Artist: "Jamie N Commons",
			Difficulty: "Hard",
		},
		{ Name: "Dang!", Artist: "Mac Miller", Difficulty: "Hard" },
		{
			Name: "So Rich, So Pretty",
			Artist: "Mickey Avalon",
			Difficulty: "Hard",
		},
		{ Name: "My Heroine", Artist: "Silverstein", Difficulty: "Hard" },
		{ Name: "Grace", Artist: "Surfaces", Difficulty: "Hard" },
		{ Name: "Highwayman", Artist: "The Highwaymen", Difficulty: "Hard" },
		{
			Name: "Reflections",
			Artist: "The Neighbourhood",
			Difficulty: "Hard",
		},
	];
	return new Response(JSON.stringify(Songs));
}
